### ISSUE TITLE
When using max2011, I made an error in selecting 'animation selector'

### ISSUE THREAD

**Issue by lcfkbs** [TaylorMouse/warcraft_III_reforged_tools#3]
![Q4(49 1Y%3MIB8AMEJ03)EX](https://user-images.githubusercontent.com/67427525/170516777-809ec945-a5ad-4f95-9d33-b6f4c8d5f683.png)

**Comment by lcfkbs** [comment]
Other versions of Max do not have such problems

**Comment by lcfkbs** [comment]
Max2011 and 2012 both have this error

**Comment by TaylorMouse** [comment]
What are you trying to play? I don't see anything in the scene ?

**Comment by lcfkbs** [comment]
I took a screenshot. Isn't it shown here?

**Comment by lcfkbs** [comment]
I took a screenshot. Isn't it shown here?

**Comment by lcfkbs** [comment]
If you can't see the screenshot here，I took a screenshot and sent it to hive messages

**Comment by lcfkbs** [comment]
I changed them into numbers. Thank you very much
