### ISSUE TITLE
import MDX

### ISSUE THREAD

**Issue by Jarek1991** [TaylorMouse/warcraft_III_reforged_tools#4]
![bug](https://user-images.githubusercontent.com/123222063/213841211-ef219cc8-2d61-4365-b2dd-7c3f18476c81.png)

**Comment by theguywhodoesntcare** [comment]
It's cuz you trying to import mdx1100 model. Use models from 1.32 patch or convert mdx1100 models to mdx1000 with Retera's Model Stuido.

**Comment by TaylorMouse** [comment]
This should be covered now
